ALTER TABLE `m_candidates` ADD `province_id` INT NOT NULL ;

update m_candidates set province_id = 1 where system_code=06;

INSERT INTO `m_candidates` (`province_id`, `display_name`, email, addr, created_at) VALUES 
(1,'Nguyễn Hà Nội','1abc@aaa.com','1 nguyen trai',now()),
(2,'Trần TP HCM','2abc@aaa.com','2 nguyen trai',now()),
(3,'Đinh Cần Thơ','3abc@aaa.com','3 nguyen trai',now()),
(4,'Nguyễn Đà Nẵng','4abc@aaa.com','4 nguyen trai',now()),
(5,'Trần Hải Phòng','5abc@aaa.com','5 nguyen trai',now()),
(6,'Đinh An Giang','6abc@aaa.com','6 nguyen trai',now()),
(7,'Đinh Bà Rịa','7abc@aaa.com','7 nguyen trai',now()),
(8,'Đỗ Bắc Giang','8abc@aaa.com','8 nguyen trai',now()),
(9,'Nguyễn Bắc Kạn','9abc@aaa.com','9 nguyen trai',now()),
(10,'Đỗ Bạc Liêu','10abc@aaa.com','10 nguyen trai',now()),
(11,'Trần Bắc Ninh','11abc@aaa.com','11 nguyen trai',now()),
(12,'Đinh Bến Tre','12abc@aaa.com','12 nguyen trai',now()),
(13,'Nguyễn Bình Định','13abc@aaa.com','13 nguyen trai',now()),
(14,'Nguyễn Bình Dương','14abc@aaa.com','14 nguyen trai',now()),
(15,'Trần Bình Phước','15abc@aaa.com','15 nguyen trai',now()),
(16,'Đỗ Bình Thuận','16abc@aaa.com','16 nguyen trai',now()),
(17,'Nguyễn Cà Mau','17abc@aaa.com','17 nguyen trai',now()),
(18,'Đinh Cao Bằng','18abc@aaa.com','18 nguyen trai',now()),
(19,'Nguyễn Đắk Lắk','19abc@aaa.com','19 nguyen trai',now()),
(20,'Đỗ Đắk Nông','20abc@aaa.com','20 nguyen trai',now()),
(21,'Nguyễn Điện Biên','21abc@aaa.com','21 nguyen trai',now()),
(22,'Trần Đồng Nai','22abc@aaa.com','22 nguyen trai',now()),
(23,'Đỗ Đồng Tháp','23abc@aaa.com','23 nguyen trai',now()),
(24,'Lương Gia Lai','24abc@aaa.com','24 nguyen trai',now()),
(25,'Nguyễn Hà Giang','25abc@aaa.com','25 nguyen trai',now()),
(26,'Lương Hà Nam','26abc@aaa.com','26 nguyen trai',now()),
(27,'Trần Hà Tĩnh','27abc@aaa.com','27 nguyen trai',now()),
(28,'Đỗ Hải Dương','28abc@aaa.com','28 nguyen trai',now()),
(29,'Đỗ Nguyễn Hậu Giang','29abc@aaa.com','29 nguyen trai',now()),
(30,'Lương Hòa Bình','30abc@aaa.com','30 nguyen trai',now()),
(31,'Lê Hưng Yên','31abc@aaa.com','31 nguyen trai',now()),
(32,'Lương Khánh Hòa','32abc@aaa.com','32 nguyen trai',now()),
(33,'Nguyễn Kiên Giang','33abc@aaa.com','33 nguyen trai',now()),
(34,'Lê Kon Tum','34abc@aaa.com','34 nguyen trai',now()),
(35,'Nguyễn Lai Châu','35abc@aaa.com','35 nguyen trai',now()),
(36,'Lâm Đồng','36abc@aaa.com','36 nguyen trai',now()),
(37,'Lương Lạng Sơn','37abc@aaa.com','37 nguyen trai',now()),
(38,'Đinh Lào Cai','38abc@aaa.com','38 nguyen trai',now()),
(39,'Lê Long An','39abc@aaa.com','39 nguyen trai',now()),
(40,'Lương Nam Định','40abc@aaa.com','40 nguyen trai',now()),
(41,'Lê Nghệ An','41abc@aaa.com','41 nguyen trai',now()),
(42,'Đỗ Ninh Bình','42abc@aaa.com','42 nguyen trai',now()),
(43,'Đinh Ninh Thuận','43abc@aaa.com','43 nguyen trai',now()),
(44,'Lương Phú Thọ','44abc@aaa.com','44 nguyen trai',now()),
(45,'Lương Phú Yên','45abc@aaa.com','45 nguyen trai',now()),
(46,'Đỗ Quảng Bình','46abc@aaa.com','46 nguyen trai',now()),
(47,'Đinh Quảng Nam','47abc@aaa.com','47 nguyen trai',now()),
(48,'Trần Quảng Ngãi','48abc@aaa.com','48 nguyen trai',now()),
(49,'Lê Quảng Ninh','49abc@aaa.com','49 nguyen trai',now()),
(50,'Lê Quảng Trị','50abc@aaa.com','50 nguyen trai',now()),
(51,'Lê Sóc Trăng','51abc@aaa.com','51 nguyen trai',now()),
(52,'Đinh Sơn La','52abc@aaa.com','52 nguyen trai',now()),
(53,'Trần Tây Ninh','53abc@aaa.com','53 nguyen trai',now()),
(54,'Thái Bình','54abc@aaa.com','54 nguyen trai',now()),
(55,'Đinh Thái Nguyên','55abc@aaa.com','55 nguyen trai',now()),
(56,'Trần Thanh Hóa','56abc@aaa.com','56 nguyen trai',now()),
(57,'Thừa Thiên Huế','57abc@aaa.com','57 nguyen trai',now()),
(58,'Nguyễn Tiền Giang','58abc@aaa.com','58 nguyen trai',now()),
(59,'Lê Trà Vinh','59abc@aaa.com','59 nguyen trai',now()),
(60,'Lê Tuyên Quang','60abc@aaa.com','60 nguyen trai',now()),
(61,'Trần Vĩnh Long','61abc@aaa.com','61 nguyen trai',now()),
(62,'Nguyễn Vĩnh Phúc','62abc@aaa.com','62 nguyen trai',now()),
(63,'Trần Yên Bái','63abc@aaa.com','63 nguyen trai',now());

update m_candidates set system_code='06', created_by = 1 ;
